import 'package:flutter/material.dart';
class AppColors {
  const AppColors._();
  static const Color primary = Color(0xFF37A6BF);
  static const Color secondary = Color(0xFFFFE24B);
  static const Color accent = Color(0xFFB0C7FF);
  static const Color transparent = Colors.transparent;
  static const Color textPrimary = Color(0xFF333333);
  static const Color textSecondary = Color(0xFF6C757D);
  static const Color textWhite = AppColors.white;
  static const Color lightBackground = Color(0xFFF6F6F6);
  static const Color darkBackground = Color(0xFF272727);
  static const Color primaryBackground = Color(0xFFF3F5FF);
  static const Color lightContainer = Color(0xFFF6F6F6);
  static const Color lightTest = Color(0xFFFBFAFF);
  static const Color lightTestDark = Color(0xFFF1F1F3);
  static const Color darkContainer = Color(0xFFFFFFFF);
  static const Color buttonPrimary = primary;
  static const Color buttonSecondary = Color(0xFF6C757D);
  static const Color buttonDisabled = Color(0xFFC4C4C4);
  static const Color borderPrimary = Color(0xFFD9D9D9);
  static const Color borderSecondary = Color(0xFFE6E6E6);
  static const Color success = Color(0xFF008000);
  static const Color error = Color(0xFFD32F2F);
  static const Color warning = Color(0xFFFFA000);
  static const Color info = Color(0xFF1976D2);
  static const Color black = Color(0xFF232323);
  static const Color darkerGrey = Color(0xFF4F4F4F);
  static const Color darkGrey = Color(0xFF939393);
  static const Color grey = Color(0xFFE0E0E0);
  static const Color softGrey = Color(0xFFF4F4F4);
  static const Color lightGrey = Color(0xFFF9F9F9);
  static const Color white = Color(0xFFFFFFFF);
}